service: node-simple-http-endpoints

provider:
  name: aws
  runtime: nodejs8.10
  profile: nodemn

plugins:
  - serverless-offline

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  authorizerFunc:
    handler: index.authorizer
  helloWorld:
    handler: index.http
    events:
      - http:
          path: http
          method: get
          cors: true
  itemsIndex:
    handler: lib/items-api.index
    events:
      - http:
          path: items
          method: get
          cors: true
          authorizer: authorizerFunc
  itemsShow:
    handler: lib/items-api.show
    events:
      - http:
          path: items/{id}
          method: get
          cors: true
          authorizer: authorizerFunc
  itemsCreate:
    handler: lib/items-api.create
    events:
      - http:
          path: items
          method: post
          cors: true
          authorizer: authorizerFunc
  itemsUpdate:
    handler: lib/items-api.update
    events:
      - http:
          path: items/{id}
          method: put
          cors: true
          authorizer: authorizerFunc
  itemsDelete:
    handler: lib/items-api.delete
    events:
      - http:
          path: items/{id}
          method: delete
          cors: true
          authorizer: authorizerFunc
